SHOW USER;

CREATE USER ADMIN_HOTEL IDENTIFIED BY "HotelDuoc2024."
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER ADMIN_HOTEL  QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO ADMIN_HOTEL;
GRANT "RESOURCE" TO ADMIN_HOTEL;
ALTER USER ADMIN_HOTEL  DEFAULT ROLE "RESOURCE";