# Generated by Django 5.1.1 on 2024-09-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desayuno_incluido', models.BooleanField(default=False)),
                ('bano_privado', models.BooleanField(default=False)),
                ('admite_mascotas', models.BooleanField(default=False)),
                ('vista', models.CharField(max_length=100)),
            ],
        ),
    ]
