# Generated by Django 5.1.1 on 2024-09-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_habitacion_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_habitaciones/'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='bano_privado',
            field=models.BooleanField(default=True),
        ),
    ]
