# Generated by Django 5.0.3 on 2024-09-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0005_habitacion_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='calificacion',
            field=models.IntegerField(default=5),
        ),
    ]
