# Generated by Django 5.0.3 on 2024-09-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0006_habitacion_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=2),
        ),
    ]
