# Generated by Django 5.0.3 on 2024-09-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0007_alter_habitacion_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='calificacion',
            field=models.IntegerField(default=5),
        ),
    ]
