# Generated by Django 5.0.3 on 2024-09-23 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0011_alter_reseña_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
