# Generated by Django 5.0.3 on 2024-09-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0012_alter_habitacion_calificacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseña',
            new_name='Resena',
        ),
    ]
