# Generated by Django 5.0.3 on 2024-09-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0013_rename_reseña_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(default='Pendiente', max_length=200),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_pago',
            field=models.BooleanField(default=False),
        ),
    ]
