# Generated by Django 5.0.3 on 2024-09-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0015_reserva_cliente_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='valor_impuesto',
            field=models.DecimalField(decimal_places=2, default=0.19, max_digits=4),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='valor_limpieza',
            field=models.IntegerField(default=12000),
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_reserva',
            field=models.IntegerField(default=0),
        ),
    ]
