# Generated by Django 5.0.3 on 2024-09-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0016_habitacion_valor_impuesto_habitacion_valor_limpieza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='valor_impuesto',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=4),
        ),
    ]
