# Generated by Django 5.0.3 on 2024-09-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0017_alter_habitacion_valor_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='valor_reserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
