# Generated by Django 5.0.3 on 2024-09-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0018_alter_reserva_valor_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='valor_reserva',
            field=models.IntegerField(default=0),
        ),
    ]
