# Generated by Django 5.0.3 on 2024-09-28 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0019_alter_reserva_valor_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=100)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.IntegerField(default=0)),
                ('estado_pago', models.BooleanField(default=False)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.reserva')),
            ],
        ),
    ]
