# Generated by Django 5.0.3 on 2024-09-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0020_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
