# Generated by Django 5.0.3 on 2024-09-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0022_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
